export const products = [
  {
    id: 'skygrid',
    name: 'SkyGrid',
    category: 'UAV operations platform',
    status: 'Built product',
    summary: 'Plan and manage UAV missions from one operational environment.',
    details: ['Plan missions', 'Prepare operations', 'Operate missions', 'Review activity'],
    proofLabel: 'Level A / Real product evidence',
    tone: 'dark',
  },
  {
    id: 'digivolt',
    name: 'DigiVolt',
    category: 'Electric mobility platform',
    status: 'In development',
    summary: 'A booking and operations platform being developed for electric rides.',
    details: ['Book', 'Match', 'Ride', 'Arrive'],
    proofLabel: 'Level B / Product visualization',
    tone: 'light',
  },
  {
    id: 'erp-pos',
    name: 'Custom ERP / POS',
    category: 'Business operations systems',
    status: 'Solution capability',
    summary: 'Connected business systems for sales, inventory and day-to-day operations.',
    details: ['POS transaction', 'Inventory', 'Operations', 'Reporting'],
    proofLabel: 'Level B / Product visualization',
    tone: 'dark',
  },
  {
    id: 'diginorth',
    name: 'DigiNorth',
    category: 'Technology community',
    status: 'Community initiative',
    summary: 'A community for people building technology in Northern Nigeria.',
    details: ['Builders', 'Learners', 'Founders', 'Collaborators'],
    proofLabel: 'Level C / Editorial / brand visual',
    tone: 'light',
  },
  {
    id: 'academy',
    name: 'Emerging Tech Academy',
    category: 'Practical technology learning',
    status: 'Learning initiative',
    summary: 'Learn technology by building with it.',
    details: ['Learn', 'Build', 'Review', 'Ship'],
    proofLabel: 'Level C / Editorial / brand visual',
    tone: 'neutral',
  },
] as const

export type ProductId = (typeof products)[number]['id']
